project_name: "TCMS Schemas"
default_status: "To Do"
statuses: ["To Do", "In Progress", "In Review", "Done"]
labels: []
definition_of_done: ["All JSON Schemas are valid", "The pipeline is passing"]
date_format: yyyy-mm-dd
max_column_width: 20
default_editor: "nvim"
auto_open_browser: true
default_port: 6420
remote_operations: true
auto_commit: false
zero_padded_ids: 3
bypass_git_hooks: false
check_active_branches: true
active_branch_days: 10
task_prefix: "SCH"
